name: personal_cv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:

  icons_launcher: any
  language_picker: any
  font_awesome_flutter: any
  flutter_map: any
  url_launcher: any
  shared_preferences: any
  flutter:
    sdk: flutter
  flutter_svg: any
  provider: ^5.0.0
  cupertino_icons: ^1.0.2

icons_launcher:
  image_path: "images/Traveling.png"
  platforms:
    android:
      enable: true

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_native_splash:

flutter_native_splash:
  color: '#a9ccb3'
  image: images/Splash.png


flutter:
  uses-material-design: true
  assets:
    - images/Me.jpg
    - images/IIT.png
    - images/Traveling.jpg
    - images/Cat.jpg
    - images/Android.webp
    - images/red.png
    - images/pick.jpg
